# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET nuget package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore EmailInvoiceExctractor
    - name: Build
      run: dotnet build --no-restore EmailInvoiceExctractor
    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -o out
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./<project>/out/*.nupkg --skip-duplicate --no-symbols true

